/**
 * Instance registry and tmux backend for the pim manager mode.
 *
 * Each instance is a full interactive pi process running inside a detached
 * tmux session on a private tmux server (socket name "pim", isolated config).
 * Instances keep running while the manager is closed; the manager re-attaches
 * to the same tmux sessions. Instance metadata lives in a JSON registry under
 * the agent dir; live telemetry comes from status/log files written by the
 * pim-status-extension loaded into every instance.
 *
 * Instances can optionally run in their own git worktree (branch pim/<name>),
 * so parallel agents never see each other's uncommitted changes.
 */

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getAgentDir } from "../../config.ts";
import type { PimStatusFile } from "./pim-status-extension.ts";

const TMUX_SOCKET_NAME = "pim";
const TMUX_SESSION_PREFIX = "pim_";

export interface InstanceWorktree {
	/** Absolute path of the worktree checkout the instance runs in. */
	path: string;
	/** Branch created for the instance (pim/<slug>). */
	branch: string;
	/** Main repository root the worktree was created from. */
	repoRoot: string;
	/** Branch the main checkout was on when the worktree was created. */
	baseBranch: string;
}

export interface InstanceRecord {
	id: string;
	name: string;
	cwd: string;
	createdAt: string;
	/** Model pattern passed to the instance at spawn, if any. */
	model?: string;
	initialTask?: string;
	worktree?: InstanceWorktree;
}

export type InstanceState = "starting" | "working" | "idle" | "exited";

export interface InstanceView extends InstanceRecord {
	state: InstanceState;
	status?: PimStatusFile;
}

interface RegistryFile {
	instances: InstanceRecord[];
}

function getPimDir(): string {
	return join(getAgentDir(), "pim");
}

function getRegistryPath(): string {
	return join(getPimDir(), "instances.json");
}

function getStatusFilePath(id: string): string {
	return join(getPimDir(), "status", `${id}.json`);
}

export function getLogFilePath(id: string): string {
	return join(getPimDir(), "logs", `${id}.jsonl`);
}

function getWorktreesDir(): string {
	return join(getPimDir(), "worktrees");
}

function getTmuxConfPath(): string {
	return join(getPimDir(), "tmux.conf");
}

function tmuxSessionName(id: string): string {
	return `${TMUX_SESSION_PREFIX}${id}`;
}

export function loadInstances(): InstanceRecord[] {
	try {
		const raw = readFileSync(getRegistryPath(), "utf8");
		const parsed = JSON.parse(raw) as RegistryFile;
		return Array.isArray(parsed.instances) ? parsed.instances : [];
	} catch {
		return [];
	}
}

function saveInstances(instances: InstanceRecord[]): void {
	const registryPath = getRegistryPath();
	mkdirSync(dirname(registryPath), { recursive: true });
	const tmpPath = `${registryPath}.${process.pid}.tmp`;
	writeFileSync(tmpPath, JSON.stringify({ instances } satisfies RegistryFile, undefined, "\t"), "utf8");
	renameSync(tmpPath, registryPath);
}

/**
 * The private tmux server reads this config instead of ~/.tmux.conf, so pim
 * fully controls keys and appearance without touching the user's tmux setup.
 */
function ensureTmuxConf(): string {
	const confPath = getTmuxConfPath();
	const conf = [
		"# Generated by pi manager (pim). Applied to the private 'pim' tmux server only.",
		"set -g extended-keys on",
		"set -g extended-keys-format csi-u",
		"set -g allow-passthrough on",
		"set -g history-limit 50000",
		"set -s escape-time 10",
		"set -g focus-events on",
		"set -g mouse on",
		"set -g status on",
		"set -g status-interval 5",
		'set -g status-style "bg=colour236,fg=colour250"',
		'set -g status-left " pim: #{session_name} "',
		"set -g status-left-length 40",
		'set -g status-right " ctrl+q: back to manager "',
		"set -g status-right-length 40",
		"set -g window-status-format ''",
		"set -g window-status-current-format ''",
		"bind-key -n C-q detach-client",
		"",
	].join("\n");
	mkdirSync(dirname(confPath), { recursive: true });
	if (!existsSync(confPath) || readFileSync(confPath, "utf8") !== conf) {
		writeFileSync(confPath, conf, "utf8");
	}
	return confPath;
}

function runTmux(args: string[]): { ok: boolean; stdout: string; stderr: string } {
	const result = spawnSync("tmux", ["-L", TMUX_SOCKET_NAME, "-f", ensureTmuxConf(), ...args], {
		encoding: "utf8",
	});
	return {
		ok: result.status === 0,
		stdout: result.stdout ?? "",
		stderr: result.stderr ?? "",
	};
}

function runGit(cwd: string, args: string[]): { ok: boolean; stdout: string; stderr: string } {
	const result = spawnSync("git", ["-C", cwd, ...args], { encoding: "utf8" });
	return {
		ok: result.status === 0,
		stdout: (result.stdout ?? "").trim(),
		stderr: (result.stderr ?? "").trim(),
	};
}

export function tmuxAvailable(): boolean {
	const result = spawnSync("tmux", ["-V"], { encoding: "utf8" });
	return result.status === 0;
}

/** Arguments for attaching to an instance; spawned by the manager with stdio inherit. */
export function tmuxAttachArgs(id: string): string[] {
	return ["-L", TMUX_SOCKET_NAME, "-f", ensureTmuxConf(), "attach-session", "-t", tmuxSessionName(id)];
}

function listLiveTmuxSessions(): Set<string> {
	const result = runTmux(["list-sessions", "-F", "#{session_name}"]);
	if (!result.ok) {
		// No server running yet means no live sessions.
		return new Set();
	}
	return new Set(
		result.stdout
			.split("\n")
			.map((line) => line.trim())
			.filter((line) => line.startsWith(TMUX_SESSION_PREFIX)),
	);
}

function shellQuote(value: string): string {
	return `'${value.replaceAll("'", `'\\''`)}'`;
}

function resolveStatusExtensionPath(): string {
	const dir = dirname(fileURLToPath(import.meta.url));
	const tsPath = join(dir, "pim-status-extension.ts");
	return existsSync(tsPath) ? tsPath : join(dir, "pim-status-extension.js");
}

/**
 * Rebuild the command that launched this process so instances run the exact
 * same pi build (works both from sources via tsx and from dist).
 */
function buildInstanceCommand(record: InstanceRecord): string {
	const nodeParts = [process.execPath, ...process.execArgv, process.argv[1]];
	const piArgs = ["-e", resolveStatusExtensionPath(), "--name", record.name];
	if (record.model) {
		piArgs.push("--model", record.model);
	}
	if (record.initialTask) {
		piArgs.push(record.initialTask);
	}
	const envPrefix = [
		`PIM_STATUS_FILE=${shellQuote(getStatusFilePath(record.id))}`,
		`PIM_LOG_FILE=${shellQuote(getLogFilePath(record.id))}`,
		`PIM_INSTANCE_ID=${shellQuote(record.id)}`,
	];
	return [...envPrefix, "exec", ...[...nodeParts, ...piArgs].map(shellQuote)].join(" ");
}

export function gitRepoRoot(cwd: string): string | undefined {
	const result = runGit(cwd, ["rev-parse", "--show-toplevel"]);
	return result.ok ? result.stdout : undefined;
}

function slugify(name: string): string {
	const slug = name
		.toLowerCase()
		.replaceAll(/[^a-z0-9]+/g, "-")
		.replaceAll(/^-+|-+$/g, "");
	return slug || "agent";
}

function createWorktree(repoRoot: string, name: string, id: string): InstanceWorktree {
	const slug = slugify(name);
	const baseBranch = runGit(repoRoot, ["rev-parse", "--abbrev-ref", "HEAD"]).stdout || "HEAD";
	let branch = `pim/${slug}`;
	if (runGit(repoRoot, ["show-ref", "--verify", "--quiet", `refs/heads/${branch}`]).ok) {
		branch = `pim/${slug}-${id}`;
	}
	const worktreePath = join(getWorktreesDir(), `${basename(repoRoot)}-${slug}-${id}`);
	mkdirSync(getWorktreesDir(), { recursive: true });
	const result = runGit(repoRoot, ["worktree", "add", worktreePath, "-b", branch]);
	if (!result.ok) {
		throw new Error(`git worktree add failed: ${result.stderr || result.stdout || "unknown error"}`);
	}
	return { path: worktreePath, branch, repoRoot, baseBranch };
}

export interface SpawnInstanceOptions {
	name?: string;
	cwd: string;
	initialPrompt?: string;
	model?: string;
	useWorktree?: boolean;
	cols?: number;
	rows?: number;
}

export function spawnInstance(options: SpawnInstanceOptions): InstanceRecord {
	const id = randomBytes(3).toString("hex");
	const name = options.name?.trim() || `agent-${id}`;

	let worktree: InstanceWorktree | undefined;
	if (options.useWorktree) {
		const repoRoot = gitRepoRoot(options.cwd);
		if (!repoRoot) {
			throw new Error(`Cannot create a worktree: ${options.cwd} is not inside a git repository.`);
		}
		worktree = createWorktree(repoRoot, name, id);
	}

	const record: InstanceRecord = {
		id,
		name,
		cwd: worktree?.path ?? options.cwd,
		createdAt: new Date().toISOString(),
		model: options.model?.trim() || undefined,
		initialTask: options.initialPrompt?.trim() || undefined,
		worktree,
	};

	rmSync(getStatusFilePath(id), { force: true });
	const result = runTmux([
		"new-session",
		"-d",
		"-s",
		tmuxSessionName(id),
		"-c",
		record.cwd,
		"-x",
		String(options.cols ?? 220),
		"-y",
		String(options.rows ?? 50),
		buildInstanceCommand(record),
	]);
	if (!result.ok) {
		throw new Error(`tmux failed to create instance session: ${result.stderr.trim() || "unknown error"}`);
	}

	const instances = loadInstances();
	instances.push(record);
	saveInstances(instances);
	return record;
}

/**
 * Kill the tmux session (if alive) and drop the instance from the registry.
 * Worktrees are intentionally left in place so uncommitted/unmerged work
 * survives; merge or remove them via git (or pi manager merge).
 */
export function removeInstance(id: string): void {
	runTmux(["kill-session", "-t", tmuxSessionName(id)]);
	rmSync(getStatusFilePath(id), { force: true });
	saveInstances(loadInstances().filter((instance) => instance.id !== id));
}

/** Type a prompt into a (possibly detached) instance and submit it. */
export function sendPrompt(id: string, text: string): void {
	const target = tmuxSessionName(id);
	const literal = runTmux(["send-keys", "-t", target, "-l", text]);
	if (!literal.ok) {
		throw new Error(`Failed to send prompt: ${literal.stderr.trim() || "unknown error"}`);
	}
	runTmux(["send-keys", "-t", target, "Enter"]);
}

/** Capture the instance's current terminal screen (what you'd see attached). */
export function capturePane(id: string): string {
	const result = runTmux(["capture-pane", "-p", "-t", tmuxSessionName(id)]);
	if (!result.ok) {
		throw new Error(`Failed to capture pane: ${result.stderr.trim() || "unknown error"}`);
	}
	return result.stdout.replace(/\s+$/, "");
}

export interface MergeResult {
	ok: boolean;
	branch: string;
	targetBranch: string;
	output: string;
}

/**
 * Merge an instance's worktree branch into the branch currently checked out
 * in the main repository root.
 */
export function mergeInstanceBranch(record: InstanceRecord): MergeResult {
	if (!record.worktree) {
		throw new Error(`Instance "${record.name}" has no worktree/branch to merge.`);
	}
	const { repoRoot, branch } = record.worktree;
	const dirty = runGit(record.worktree.path, ["status", "--porcelain"]);
	if (dirty.ok && dirty.stdout.length > 0) {
		throw new Error(
			`Worktree for "${record.name}" has uncommitted changes. Commit them in ${record.worktree.path} first.`,
		);
	}
	const targetBranch = runGit(repoRoot, ["rev-parse", "--abbrev-ref", "HEAD"]).stdout || "HEAD";
	const result = runGit(repoRoot, ["merge", "--no-ff", branch, "-m", `Merge ${branch} (pim instance ${record.name})`]);
	return {
		ok: result.ok,
		branch,
		targetBranch,
		output: [result.stdout, result.stderr].filter(Boolean).join("\n"),
	};
}

function readStatusFile(id: string): PimStatusFile | undefined {
	try {
		return JSON.parse(readFileSync(getStatusFilePath(id), "utf8")) as PimStatusFile;
	} catch {
		return undefined;
	}
}

export function getInstanceViews(): InstanceView[] {
	const liveSessions = listLiveTmuxSessions();
	const views = loadInstances().map((record): InstanceView => {
		if (!liveSessions.has(tmuxSessionName(record.id))) {
			return { ...record, state: "exited" };
		}
		const status = readStatusFile(record.id);
		if (!status || status.state === "exited") {
			// Session is alive but the agent has not reported yet (still booting)
			// or is shutting down.
			return { ...record, state: "starting", status };
		}
		return { ...record, state: status.state, status };
	});
	return views.sort((a, b) => a.createdAt.localeCompare(b.createdAt));
}

/** Resolve an instance by id, id prefix, or exact name. */
export function findInstance(idOrName: string): InstanceRecord | undefined {
	const instances = loadInstances();
	return (
		instances.find((instance) => instance.id === idOrName) ??
		instances.find((instance) => instance.name === idOrName) ??
		instances.find((instance) => instance.id.startsWith(idOrName))
	);
}

export function formatInstanceCwd(cwd: string): string {
	const home = homedir();
	return cwd.startsWith(home) ? `~${cwd.slice(home.length)}` : cwd;
}
